services:
  mysql:
    image: mysql:8.0
    privileged: true
    container_name: pump-watch-mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: '0000'
      MYSQL_DATABASE: 'pump_watch'
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql

  nestjs:
    image: medazizbendhiab/pump-watch-backend
    privileged: true
    container_name: pump-watch-backend-container
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - mysql
    environment:
      DB_HOST: my-mysql-container
      DB_PORT: 3306
      DB_USERNAME: root
      DB_PASSWORD: '0000'
      DB_DATABASE: service_com

volumes:
  mysql-data:
